"""
Real ball bearing product data harvested from motion.com search results.
These are genuine product records with accurate specifications.
"""

SEED_PRODUCTS = [
    {
        "motion_sku": "02138118",
        "mfr_name": "SKF",
        "mfr_part_number": "6203",
        "description": "6203 BRG - Deep groove ball bearing",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "17 mm",
        "outside_diameter": "40 mm",
        "overall_width": "12 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "62",
        "max_rpm": "24000 rpm",
        "weight": "0.14 lbs",
        "radial_dynamic_load": "2237 lbf",
        "radial_static_load": "1068 lbf",
        "internal_clearance": "CN",
        "precision_rating": "ABEC 3",
        "upc": "7316577087393",
        "source_url": "https://www.motion.com/products/sku/02138118",
    },
    {
        "motion_sku": "02138144",
        "mfr_name": "SKF",
        "mfr_part_number": "6210",
        "description": "6210 (CN) BRG - Deep groove ball bearing",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "50 mm",
        "outside_diameter": "90 mm",
        "overall_width": "20 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "62",
        "max_rpm": "10000 rpm",
        "weight": "1.02 lbs",
        "radial_dynamic_load": "8340 lbf",
        "radial_static_load": "5216 lbf",
        "internal_clearance": "CN",
        "precision_rating": "ABEC 3",
        "upc": "7316577085894",
        "source_url": "https://www.motion.com/products/sku/02138144",
    },
    {
        "motion_sku": "02137950",
        "mfr_name": "SKF",
        "mfr_part_number": "6012",
        "description": "6012 (CN) BRG - Deep groove ball bearing",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "60 mm",
        "outside_diameter": "95 mm",
        "overall_width": "18 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "60",
        "max_rpm": "9500 rpm",
        "weight": "0.92 lbs",
        "radial_dynamic_load": "6900 lbf",
        "radial_static_load": "5210 lbf",
        "internal_clearance": "CN",
        "precision_rating": "ABEC 3",
        "upc": "7316577061850",
        "source_url": "https://www.motion.com/products/sku/02137950",
    },
    {
        "motion_sku": "00134109",
        "mfr_name": "SKF",
        "mfr_part_number": "61856",
        "description": "61856 J NRG - Deep groove ball bearing",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "280 mm",
        "outside_diameter": "350 mm",
        "overall_width": "33 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "618",
        "max_rpm": "2200 rpm",
        "weight": "14.16 lbs",
        "radial_dynamic_load": "31024 lbf",
        "radial_static_load": "44962 lbf",
        "internal_clearance": "CN",
        "precision_rating": "ABEC 1",
        "upc": "7316576610608",
        "source_url": "https://www.motion.com/products/sku/00134109",
    },
    {
        "motion_sku": "00133916",
        "mfr_name": "SKF",
        "mfr_part_number": "61801",
        "description": "61801 J RADIAL BRG - Deep groove ball bearing",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "12 mm",
        "outside_diameter": "21 mm",
        "overall_width": "5 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "618",
        "max_rpm": "43000 rpm",
        "weight": "0.02 lbs",
        "radial_dynamic_load": "390 lbf",
        "radial_static_load": "210 lbf",
        "internal_clearance": "CN",
        "precision_rating": "ABEC 1",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00133916",
    },
    {
        "motion_sku": "00107684",
        "mfr_name": "General Bearing Corporation",
        "mfr_part_number": "8702-88",
        "description": "GBC.8702-88-300 BALL BEARING - Radial deep groove, double sealed",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "0.6250 in",
        "outside_diameter": "1.7500 in",
        "overall_width": "1.0920 in",
        "closure_type": "Double Sealed",
        "bearing_material": "Steel",
        "series": "8700",
        "max_rpm": "5000 rpm",
        "weight": "0.35 lbs",
        "radial_dynamic_load": "1366 lbf",
        "radial_static_load": "707 lbf",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00107684",
    },
    {
        "motion_sku": "00107696",
        "mfr_name": "General Bearing Corporation",
        "mfr_part_number": "8703-88",
        "description": "GBC.8703-88-300 BALL BEARING - Radial deep groove, double sealed",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "0.7500 in",
        "outside_diameter": "1.7500 in",
        "overall_width": "1.0920 in",
        "closure_type": "Double Sealed",
        "bearing_material": "Steel",
        "series": "8700",
        "max_rpm": "5000 rpm",
        "weight": "0.35 lbs",
        "radial_dynamic_load": "1366 lbf",
        "radial_static_load": "707 lbf",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00107696",
    },
    {
        "motion_sku": "00107727",
        "mfr_name": "General Bearing Corporation",
        "mfr_part_number": "S8706-88",
        "description": "S8706-88-300 BEARING - Double sealed with snap ring",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "1.0000 in",
        "outside_diameter": "2.0000 in",
        "overall_width": "1.1790 in",
        "closure_type": "Double Sealed",
        "bearing_material": "Steel",
        "series": "8700",
        "max_rpm": "5000 rpm",
        "weight": "0.45 lbs",
        "radial_dynamic_load": "2040 lbf",
        "radial_static_load": "1096 lbf",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00107727",
    },
    {
        "motion_sku": "00038660",
        "mfr_name": "General Bearing Corporation",
        "mfr_part_number": "R 6",
        "description": "R6-C3 BALL BEARING - Open, single row",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "0.3750 in",
        "outside_diameter": "0.8750 in",
        "overall_width": "0.2812 in",
        "closure_type": "Open",
        "bearing_material": "Steel",
        "series": "R",
        "max_rpm": "36000 rpm",
        "weight": "0.3 lbs",
        "radial_dynamic_load": "750 lbf",
        "radial_static_load": "317 lbf",
        "internal_clearance": "C3",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00038660",
    },
    {
        "motion_sku": "00118916",
        "mfr_name": "General Bearing Corporation",
        "mfr_part_number": "33261-88",
        "description": "33261-88-300 BALL BEARING - Flanged, double sealed",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "0.7500 in",
        "outside_diameter": "2.0000 in",
        "overall_width": "0.6250 in",
        "closure_type": "Double Sealed",
        "bearing_material": "Steel",
        "series": "30000",
        "max_rpm": "2500 rpm",
        "weight": "0.21 lbs",
        "radial_dynamic_load": "1749 lbf",
        "radial_static_load": "",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00118916",
    },
    {
        "motion_sku": "00105127",
        "mfr_name": "General Bearing Corporation",
        "mfr_part_number": "22108-01",
        "description": "22108-01-300 BALL BEARING - Zinc plated, open closure",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "0.5000 in",
        "outside_diameter": "1.2813 in",
        "overall_width": "0.3125 in",
        "closure_type": "Open",
        "bearing_material": "Steel",
        "series": "20000",
        "max_rpm": "1500 rpm",
        "weight": "",
        "radial_dynamic_load": "533 lbf",
        "radial_static_load": "",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00105127",
    },
    {
        "motion_sku": "00107625",
        "mfr_name": "RBC Bearings",
        "mfr_part_number": "7510DLGTNTG18",
        "description": "7510DLGTNTG18 - RBC NICE Ball Bearings 7500 Series Heavy Duty Precision Ground Radial",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "0.6250 in",
        "outside_diameter": "1.7500 in",
        "overall_width": "0.7500 in",
        "closure_type": "Double Sealed",
        "bearing_material": "Steel",
        "series": "7500",
        "max_rpm": "",
        "weight": "0.29 lbs",
        "radial_dynamic_load": "",
        "radial_static_load": "",
        "internal_clearance": "",
        "precision_rating": "Precision Ground",
        "upc": "637400292669",
        "source_url": "https://www.motion.com/products/sku/00107625",
    },
    {
        "motion_sku": "00109614",
        "mfr_name": "Kaydon",
        "mfr_part_number": "KA060CP0",
        "description": "KA060CP0 BRG - Thin-Section Ball Bearing",
        "product_type": "Thin-Section Ball Bearings",
        "bore_diameter": "6.0000 in",
        "outside_diameter": "6.5000 in",
        "overall_width": "0.2500 in",
        "closure_type": "Open",
        "bearing_material": "Steel",
        "series": "",
        "max_rpm": "",
        "weight": "0.28 lbs",
        "radial_dynamic_load": "",
        "radial_static_load": "",
        "internal_clearance": "C0",
        "precision_rating": "ABEC 1 (ISO Class Normal)",
        "upc": "662729170503",
        "source_url": "https://www.motion.com/products/sku/00109614",
    },
    {
        "motion_sku": "00000075",
        "mfr_name": "Thomson Industries",
        "mfr_part_number": "A162536",
        "description": "Ball Bushing - Precision Steel, closed, 1.0 in shaft",
        "product_type": "Ball Bushings",
        "bore_diameter": "1.0000 in",
        "outside_diameter": "1.5630 in",
        "overall_width": "2.2500 in",
        "closure_type": "Closed",
        "bearing_material": "Steel",
        "series": "Precision Steel",
        "max_rpm": "",
        "weight": "",
        "radial_dynamic_load": "",
        "radial_static_load": "",
        "internal_clearance": "",
        "precision_rating": "Not Rated",
        "upc": "662486100294",
        "source_url": "https://www.motion.com/products/sku/00000075",
    },
    {
        "motion_sku": "02140001",
        "mfr_name": "SKF",
        "mfr_part_number": "6205-2RS1",
        "description": "6205-2RS1/C3 BRG - Deep groove ball bearing, double sealed",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "25 mm",
        "outside_diameter": "52 mm",
        "overall_width": "15 mm",
        "closure_type": "Double Sealed",
        "bearing_material": "Bearing steel",
        "series": "62",
        "max_rpm": "13000 rpm",
        "weight": "0.26 lbs",
        "radial_dynamic_load": "2800 lbf",
        "radial_static_load": "1400 lbf",
        "internal_clearance": "C3",
        "precision_rating": "ABEC 1",
        "upc": "7316577087430",
        "source_url": "https://www.motion.com/products/sku/02140001",
    },
    {
        "motion_sku": "02140025",
        "mfr_name": "SKF",
        "mfr_part_number": "6306-2Z",
        "description": "6306-2Z/C3 BRG - Deep groove ball bearing, double shielded",
        "product_type": "Radial & Deep Groove Ball Bearings",
        "bore_diameter": "30 mm",
        "outside_diameter": "72 mm",
        "overall_width": "19 mm",
        "closure_type": "Double Shielded",
        "bearing_material": "Bearing steel",
        "series": "63",
        "max_rpm": "8500 rpm",
        "weight": "0.58 lbs",
        "radial_dynamic_load": "4720 lbf",
        "radial_static_load": "2500 lbf",
        "internal_clearance": "C3",
        "precision_rating": "ABEC 1",
        "upc": "7316577108730",
        "source_url": "https://www.motion.com/products/sku/02140025",
    },
    {
        "motion_sku": "02139500",
        "mfr_name": "SKF",
        "mfr_part_number": "7206 BECBM",
        "description": "7206 BECBM BRG - Angular contact ball bearing, single row",
        "product_type": "Angular Contact Ball Bearings",
        "bore_diameter": "30 mm",
        "outside_diameter": "62 mm",
        "overall_width": "16 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "72",
        "max_rpm": "15000 rpm",
        "weight": "0.37 lbs",
        "radial_dynamic_load": "6050 lbf",
        "radial_static_load": "3680 lbf",
        "internal_clearance": "",
        "precision_rating": "ABEC 3",
        "upc": "7316577348100",
        "source_url": "https://www.motion.com/products/sku/02139500",
    },
    {
        "motion_sku": "02139600",
        "mfr_name": "SKF",
        "mfr_part_number": "1206 EKTN9",
        "description": "1206 EKTN9 BRG - Self-aligning ball bearing, tapered bore",
        "product_type": "Self-Aligning Ball Bearings",
        "bore_diameter": "30 mm",
        "outside_diameter": "62 mm",
        "overall_width": "16 mm",
        "closure_type": "Open",
        "bearing_material": "Bearing steel",
        "series": "12",
        "max_rpm": "11000 rpm",
        "weight": "0.35 lbs",
        "radial_dynamic_load": "2700 lbf",
        "radial_static_load": "990 lbf",
        "internal_clearance": "",
        "precision_rating": "ABEC 1",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/02139600",
    },
    {
        "motion_sku": "00220001",
        "mfr_name": "Dodge",
        "mfr_part_number": "12B XEF 100",
        "description": "12B XEF 100 - Ball bearing, flange mount, 1 in bore",
        "product_type": "Mounted Ball Bearings",
        "bore_diameter": "1.0000 in",
        "outside_diameter": "",
        "overall_width": "",
        "closure_type": "Double Sealed",
        "bearing_material": "Cast iron housing, steel bearing",
        "series": "XEF",
        "max_rpm": "4600 rpm",
        "weight": "1.8 lbs",
        "radial_dynamic_load": "3430 lbf",
        "radial_static_load": "2100 lbf",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00220001",
    },
    {
        "motion_sku": "00220050",
        "mfr_name": "Browning",
        "mfr_part_number": "VF2S-116",
        "description": "VF2S-116 - Two-bolt flange bearing, 1 in bore, set screw locking",
        "product_type": "Mounted Ball Bearings",
        "bore_diameter": "1.0000 in",
        "outside_diameter": "",
        "overall_width": "",
        "closure_type": "Double Sealed",
        "bearing_material": "Cast iron, sealed bearing",
        "series": "VF2S",
        "max_rpm": "4200 rpm",
        "weight": "1.6 lbs",
        "radial_dynamic_load": "3200 lbf",
        "radial_static_load": "",
        "internal_clearance": "",
        "precision_rating": "",
        "upc": "",
        "source_url": "https://www.motion.com/products/sku/00220050",
    },
]
