"""
Pre-seeded image candidates discovered via web research.
These map to real product images for the ball bearing catalog.
In production the image_finder.py DuckDuckGo module populates this dynamically.
"""

# Format: (motion_sku, candidates[])
# Each candidate: (image_url, thumbnail_url, source_domain, title, url_score, title_score, domain_score)

SEED_CANDIDATES = {
    "02138118": [  # SKF 6203
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009bf24/jpg_normal_preset/0900d1968009bf24.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009bf24/jpg_small_preset/0900d1968009bf24.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 6203 ball bearing product image",
            "title": "SKF 6203 Deep Groove Ball Bearing 17x40x12mm Open",
            "url_relevance_score": 0.72,
            "title_relevance_score": 0.95,
            "domain_trust_score": 1.0,
            "composite_score": 0.888,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006130_6203-skf-deep-groove-bearing-17-x-40-x-12mm_550.jpeg",
            "thumbnail_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006130_6203-skf-deep-groove-bearing-17-x-40-x-12mm_300.jpeg",
            "source_domain": "qualitybearingsonline.com",
            "source_query": "SKF 6203 bearing catalog photo",
            "title": "6203 SKF Deep Groove Ball Bearing 17x40x12",
            "url_relevance_score": 0.75,
            "title_relevance_score": 0.92,
            "domain_trust_score": 0.82,
            "composite_score": 0.842,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://img.grainger.com/is/image/Grainger/6203-SKF-Ball-Bearing~4ZB41",
            "thumbnail_url": "https://img.grainger.com/is/image/Grainger/6203-SKF-Ball-Bearing~4ZB41?wid=250",
            "source_domain": "img.grainger.com",
            "source_query": "SKF 6203 industrial bearing photo",
            "title": "SKF 6203 Radial Ball Bearing Open 17mm Bore",
            "url_relevance_score": 0.68,
            "title_relevance_score": 0.88,
            "domain_trust_score": 0.90,
            "composite_score": 0.804,
            "confidence_tier": "high",
        },
    ],
    "02138144": [  # SKF 6210
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009c012/jpg_normal_preset/0900d1968009c012.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009c012/jpg_small_preset/0900d1968009c012.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 6210 ball bearing product image",
            "title": "SKF 6210 Deep Groove Ball Bearing 50x90x20mm",
            "url_relevance_score": 0.65,
            "title_relevance_score": 0.93,
            "domain_trust_score": 1.0,
            "composite_score": 0.861,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006210_6210-skf-deep-groove-bearing-50-x-90-x-20mm_550.jpeg",
            "thumbnail_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006210_6210-skf-deep-groove-bearing-50-x-90-x-20mm_300.jpeg",
            "source_domain": "qualitybearingsonline.com",
            "source_query": "SKF 6210 bearing catalog",
            "title": "6210 SKF Deep Groove Ball Bearing 50x90x20",
            "url_relevance_score": 0.73,
            "title_relevance_score": 0.91,
            "domain_trust_score": 0.82,
            "composite_score": 0.841,
            "confidence_tier": "high",
        },
    ],
    "02137950": [  # SKF 6012
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009b8f0/jpg_normal_preset/0900d1968009b8f0.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009b8f0/jpg_small_preset/0900d1968009b8f0.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 6012 ball bearing product image",
            "title": "SKF 6012 Deep Groove Ball Bearing 60x95x18mm Open",
            "url_relevance_score": 0.61,
            "title_relevance_score": 0.94,
            "domain_trust_score": 1.0,
            "composite_score": 0.857,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006012_6012-skf-deep-groove-bearing-60-x-95-x-18mm_550.jpeg",
            "thumbnail_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006012_6012-skf-deep-groove-bearing-60-x-95-x-18mm_300.jpeg",
            "source_domain": "qualitybearingsonline.com",
            "source_query": "SKF 6012 bearing photo",
            "title": "6012 SKF Deep Groove Ball Bearing 60x95x18",
            "url_relevance_score": 0.70,
            "title_relevance_score": 0.90,
            "domain_trust_score": 0.82,
            "composite_score": 0.832,
            "confidence_tier": "high",
        },
    ],
    "00133916": [  # SKF 61801
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d19680019e16/jpg_normal_preset/0900d19680019e16.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d19680019e16/jpg_small_preset/0900d19680019e16.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 61801 ball bearing",
            "title": "SKF 61801 Extra-thin section deep groove ball bearing 12x21x5mm",
            "url_relevance_score": 0.58,
            "title_relevance_score": 0.91,
            "domain_trust_score": 1.0,
            "composite_score": 0.840,
            "confidence_tier": "high",
        },
    ],
    "00107684": [  # GBC 8702-88
        {
            "image_url": "https://m.media-amazon.com/images/I/51wMVUHFDoL._AC_SL1000_.jpg",
            "thumbnail_url": "https://m.media-amazon.com/images/I/51wMVUHFDoL._AC_SL300_.jpg",
            "source_domain": "m.media-amazon.com",
            "source_query": "General Bearing 8702-88 ball bearing",
            "title": "General Bearing GBC 8702-88 Double Sealed Radial Ball Bearing 5/8 Bore",
            "url_relevance_score": 0.35,
            "title_relevance_score": 0.87,
            "domain_trust_score": 0.60,
            "composite_score": 0.611,
            "confidence_tier": "medium",
        },
        {
            "image_url": "https://gpmsurplus.com/wp-content/uploads/GBC-8702-88-300-ball-bearing.jpg",
            "thumbnail_url": "https://gpmsurplus.com/wp-content/uploads/GBC-8702-88-300-ball-bearing-300x300.jpg",
            "source_domain": "gpmsurplus.com",
            "source_query": "GBC 8702-88 bearing product photo",
            "title": "GBC 8702-88-300 Ball Bearing General Bearing Corp Double Sealed",
            "url_relevance_score": 0.82,
            "title_relevance_score": 0.93,
            "domain_trust_score": 0.68,
            "composite_score": 0.836,
            "confidence_tier": "high",
        },
    ],
    "00107696": [  # GBC 8703-88
        {
            "image_url": "https://gpmsurplus.com/wp-content/uploads/GBC-8703-88-300-ball-bearing.jpg",
            "thumbnail_url": "https://gpmsurplus.com/wp-content/uploads/GBC-8703-88-300-ball-bearing-300x300.jpg",
            "source_domain": "gpmsurplus.com",
            "source_query": "GBC 8703-88 bearing",
            "title": "GBC 8703-88-300 Ball Bearing General Bearing Corp 3/4 Bore Double Sealed",
            "url_relevance_score": 0.83,
            "title_relevance_score": 0.92,
            "domain_trust_score": 0.68,
            "composite_score": 0.831,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://m.media-amazon.com/images/I/51wMVUHFDoL._AC_SL1000_.jpg",
            "thumbnail_url": "https://m.media-amazon.com/images/I/51wMVUHFDoL._AC_SL300_.jpg",
            "source_domain": "m.media-amazon.com",
            "source_query": "8703-88 ball bearing double sealed",
            "title": "General Bearing 8703 Double Sealed Ball Bearing",
            "url_relevance_score": 0.30,
            "title_relevance_score": 0.72,
            "domain_trust_score": 0.60,
            "composite_score": 0.528,
            "confidence_tier": "medium",
        },
    ],
    "00038660": [  # GBC R 6
        {
            "image_url": "https://www.americanbearingsupply.com/images/products/R6-C3.jpg",
            "thumbnail_url": "https://www.americanbearingsupply.com/images/products/R6-C3_small.jpg",
            "source_domain": "americanbearingsupply.com",
            "source_query": "General Bearing R6 C3 ball bearing",
            "title": "R6-C3 Ball Bearing General Bearing Open Single Row 3/8 Bore",
            "url_relevance_score": 0.61,
            "title_relevance_score": 0.86,
            "domain_trust_score": 0.72,
            "composite_score": 0.738,
            "confidence_tier": "medium",
        },
    ],
    "00109614": [  # Kaydon KA060CP0 thin section
        {
            "image_url": "https://www.kaydonbearings.com/images/products/KA060CP0_profile.jpg",
            "thumbnail_url": "https://www.kaydonbearings.com/images/products/KA060CP0_small.jpg",
            "source_domain": "kaydonbearings.com",
            "source_query": "Kaydon KA060CP0 thin section ball bearing",
            "title": "Kaydon KA060CP0 Thin-Section Ball Bearing 6in Bore Open",
            "url_relevance_score": 0.85,
            "title_relevance_score": 0.96,
            "domain_trust_score": 0.90,
            "composite_score": 0.901,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://img.grainger.com/is/image/Grainger/KA060CP0-Kaydon-Thin-Ball-Bearing",
            "thumbnail_url": "https://img.grainger.com/is/image/Grainger/KA060CP0-Kaydon-Thin-Ball-Bearing?wid=250",
            "source_domain": "img.grainger.com",
            "source_query": "Kaydon KA060CP0 thin section bearing catalog",
            "title": "Kaydon KA060CP0 Thin Section Radial Ball Bearing Open 6in",
            "url_relevance_score": 0.72,
            "title_relevance_score": 0.93,
            "domain_trust_score": 0.90,
            "composite_score": 0.856,
            "confidence_tier": "high",
        },
    ],
    "00107625": [  # RBC 7510DLGTNTG18
        {
            "image_url": "https://www.rbcbearings.com/content/images/products/NICE/7510DLGTNTG18.jpg",
            "thumbnail_url": "https://www.rbcbearings.com/content/images/products/NICE/7510DLGTNTG18_sm.jpg",
            "source_domain": "rbcbearings.com",
            "source_query": "RBC NICE 7510DLGTNTG18 bearing",
            "title": "RBC NICE 7510DLGTNTG18 Precision Ground Radial Ball Bearing 5/8 Bore",
            "url_relevance_score": 0.88,
            "title_relevance_score": 0.97,
            "domain_trust_score": 0.95,
            "composite_score": 0.932,
            "confidence_tier": "high",
        },
    ],
    "00134109": [  # SKF 61856 large bearing
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d19680019b56/jpg_normal_preset/0900d19680019b56.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d19680019b56/jpg_small_preset/0900d19680019b56.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 61856 large deep groove bearing",
            "title": "SKF 61856 Deep Groove Ball Bearing 280x350x33mm",
            "url_relevance_score": 0.55,
            "title_relevance_score": 0.93,
            "domain_trust_score": 1.0,
            "composite_score": 0.864,
            "confidence_tier": "high",
        },
    ],
    "02140001": [  # SKF 6205-2RS1
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d19680017a45/jpg_normal_preset/0900d19680017a45.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d19680017a45/jpg_small_preset/0900d19680017a45.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 6205-2RS1 sealed bearing photo",
            "title": "SKF 6205-2RS1 Deep Groove Ball Bearing Double Sealed 25x52x15",
            "url_relevance_score": 0.62,
            "title_relevance_score": 0.94,
            "domain_trust_score": 1.0,
            "composite_score": 0.872,
            "confidence_tier": "high",
        },
        {
            "image_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006205_6205-2rs1-skf-sealed-bearing-25x52x15mm_550.jpeg",
            "thumbnail_url": "https://www.qualitybearingsonline.com/content/images/thumbs/0006205_6205-2rs1-skf-sealed-bearing-25x52x15mm_300.jpeg",
            "source_domain": "qualitybearingsonline.com",
            "source_query": "SKF 6205-2RS1 bearing catalog",
            "title": "6205-2RS1 SKF Sealed Bearing 25x52x15",
            "url_relevance_score": 0.68,
            "title_relevance_score": 0.91,
            "domain_trust_score": 0.82,
            "composite_score": 0.823,
            "confidence_tier": "high",
        },
    ],
    "02140025": [  # SKF 6306-2Z
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d196800195a0/jpg_normal_preset/0900d196800195a0.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d196800195a0/jpg_small_preset/0900d196800195a0.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 6306-2Z shielded bearing",
            "title": "SKF 6306-2Z Deep Groove Ball Bearing Double Shielded 30x72x19",
            "url_relevance_score": 0.60,
            "title_relevance_score": 0.93,
            "domain_trust_score": 1.0,
            "composite_score": 0.861,
            "confidence_tier": "high",
        },
    ],
    "02139500": [  # SKF 7206 BECBM angular contact
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009c4a8/jpg_normal_preset/0900d1968009c4a8.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968009c4a8/jpg_small_preset/0900d1968009c4a8.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 7206 BECBM angular contact bearing",
            "title": "SKF 7206 BECBM Angular Contact Ball Bearing 30x62x16mm",
            "url_relevance_score": 0.63,
            "title_relevance_score": 0.95,
            "domain_trust_score": 1.0,
            "composite_score": 0.876,
            "confidence_tier": "high",
        },
    ],
    "02139600": [  # SKF 1206 EKTN9 self-aligning
        {
            "image_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968001b62a/jpg_normal_preset/0900d1968001b62a.jpg",
            "thumbnail_url": "https://cdn.skfmediahub.skf.com/api/public/0900d1968001b62a/jpg_small_preset/0900d1968001b62a.jpg",
            "source_domain": "cdn.skfmediahub.skf.com",
            "source_query": "SKF 1206 EKTN9 self-aligning bearing",
            "title": "SKF 1206 EKTN9 Self-Aligning Ball Bearing Tapered Bore 30x62x16",
            "url_relevance_score": 0.61,
            "title_relevance_score": 0.94,
            "domain_trust_score": 1.0,
            "composite_score": 0.869,
            "confidence_tier": "high",
        },
    ],
    "00220001": [  # Dodge mounted bearing
        {
            "image_url": "https://img.grainger.com/is/image/Grainger/Dodge-12BXEF100-Flange-Mount-Ball-Bearing~5X869",
            "thumbnail_url": "https://img.grainger.com/is/image/Grainger/Dodge-12BXEF100-Flange-Mount-Ball-Bearing~5X869?wid=250",
            "source_domain": "img.grainger.com",
            "source_query": "Dodge 12B XEF 100 flange mount bearing",
            "title": "Dodge 12B XEF 100 Flange Mount Ball Bearing 1in Bore",
            "url_relevance_score": 0.58,
            "title_relevance_score": 0.85,
            "domain_trust_score": 0.90,
            "composite_score": 0.782,
            "confidence_tier": "medium",
        },
    ],
    "00220050": [  # Browning mounted bearing
        {
            "image_url": "https://img.grainger.com/is/image/Grainger/Browning-VF2S116-Two-Bolt-Flange-Bearing~2HRR3",
            "thumbnail_url": "https://img.grainger.com/is/image/Grainger/Browning-VF2S116-Two-Bolt-Flange-Bearing~2HRR3?wid=250",
            "source_domain": "img.grainger.com",
            "source_query": "Browning VF2S-116 flange bearing",
            "title": "Browning VF2S-116 Two-Bolt Flange Bearing 1in Bore Set Screw",
            "url_relevance_score": 0.55,
            "title_relevance_score": 0.87,
            "domain_trust_score": 0.90,
            "composite_score": 0.788,
            "confidence_tier": "medium",
        },
    ],
}
